version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fitico_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fitico_db
      MYSQL_USER: fitico_user
      MYSQL_PASSWORD: fitico_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
